### PR TITLE
Add black, pylint pre-commit hooks and workflow actions

### PR DESCRIPTION
**Pull request by ameyakhare**
Adds pre-commit and black + pylint as a pre-commit hooks and workflow actions.

Will add mypy in another change since it requires a lot of updates to our existing files.

### CODE REVIEW

**Comment by ericliuche** [comment]
Drive by comment: in the past we've always preferred pylint over flake8

**Comment by ameyakhare** [comment]
> Drive by comment: in my past jobs we've always preferred pylint over flake8

I'm going to be adding both

**Comment by ericliuche** [comment]
Typically you don't want both because they sometimes conflict. You want to choose one or the other

**Comment by ameyakhare** [comment]
hmm for a project of this size it seems like pylint might actually be pretty overkill, it has a high rate of false positives and is quite a bit more annoying to set up

**Pull request merged**
